events {
    worker_connections 1024;
}

http {
    upstream backend {
        server app-stable:5000 weight=8;
        server app-canary:5000 weight=2;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /stable/ {
            proxy_pass http://app-stable:5000/;
            proxy_set_header Host $host;
        }

        location /canary/ {
            proxy_pass http://app-canary:5000/;
            proxy_set_header Host $host;
        }

        location /nginx_status {
            stub_status on;
            allow all;
        }
    }
}